name: Audio-To-Text Workflow

on:
  workflow_dispatch:

jobs:
  transcribe_audio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      # - name: Install packages and dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pydub SpeechRecognition
      #     sudo apt-get update
      #     sudo apt-get install ffmpeg
      
      # - name: Analysing the code with pylint
      #   run: |
      #     pylint $(git ls-files '*.py')
      #   continue-on-error: true

      # - name: Test with pytest
      #   run: |
      #     pytest -v -rA test/
          
      - name: Execute Python script
        run: |
          python src/transcription.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index HEAD || (git commit -a -m "updated transcribed files")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # summarize_text:
  #   needs: transcribe_audio
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo content
  #       uses: actions/checkout@v4

  #     - name: Set up python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'
          
  #     - name: Install python packages
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install langchain_community langchain_core langchain_openai
      
  #     # - name: Analysing the code with pylint
  #     #   run: |
  #     #     pylint $(git ls-files '*.py')
  #     #   continue-on-error: true

  #     # - name: Test with pytest
  #     #   run: |
  #     #     pytest -v -rA test/
          
  #     - name: Execute Python script
  #       run: |
  #         python src/summarization.py
  #       env:
  #         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
  #     - name: Commit files
  #       run: |
  #         git config --local user.email "action@github.com"
  #         git config --local user.name "GitHub Action"
  #         git add -A
  #         git diff-index HEAD || (git commit -a -m "updated summarised files")