name: Audio-To-Text Workflow

on:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install packages and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Linting
        run: |
          pylint $(git ls-files '*.py')
        continue-on-error: true

  transcribe_audio:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install packages and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydub SpeechRecognition
          sudo apt-get update
          sudo apt-get install ffmpeg
          
      - name: Execute Python script
        run: |
          python src/transcription.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated transcribed file" --allow-empty)
          git push

  summarize_text:
    needs: transcribe_audio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Take Pull
        run: |
          git pull

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install langchain_community langchain_core langchain_openai
          
      - name: Execute Python script
        run: |
          python src/summarization.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated summarisation in file" --allow-empty)
          git push
